language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm

# also test against HHVM, but require "trusty" and ignore errors
matrix:
  allow_failures:
    - php: hhvm

before_script: composer install

script:
  - phpunit --testsuite travis-ci
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
